/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 carrot.glb -t -T 
Files: carrot.glb [8.56KB] > /home/jax/Desktop/personal/philanthropy-clinic/carrot-transformed.glb [2.47KB] (71%)
*/

import * as THREE from 'three'
import {Mesh} from 'three'
import {useGLTF, useKTX2} from '@react-three/drei'
import type {GLTF} from 'three-stdlib';
import type {JSX} from "react/jsx-runtime";
import {useEffect, useRef, useState} from "react";
import {useFrame} from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    carrot: THREE.Mesh
  }
  materials: {
    carrot: THREE.MeshStandardMaterial
  }
}

export function Carrot(props: JSX.IntrinsicElements['group'] & {jailState?: boolean}) {
  const { nodes } = useGLTF('/models/carrot-transformed.glb') as unknown as GLTFResult

  const [hovered, setHovered] = useState(false)

  const groupRef = useRef<Mesh>(null!);
  useFrame(() => {
    if (groupRef.current) {
      groupRef.current.rotation.y -= 0.02;
    }
  });

  const [baseMap] = useKTX2([
    '/textures/carrot.ktx2',
  ])

  useEffect(() => {
    if (!props.jailState) return;
    document.body.style.cursor = hovered ? "pointer" : "default";
  }, [hovered, props.jailState]);

  return (
    <group {...props} dispose={null} ref={groupRef} onPointerOver={()=>setHovered(true)} onPointerOut={() => setHovered(false)}>
      <mesh geometry={nodes.carrot.geometry}>
        <meshStandardMaterial map={baseMap}/>
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/carrot-transformed.glb')
