/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 1dollar.glb -T -t 
Files: 1dollar.glb [285.8KB] > /home/jax/Desktop/personal/philanthropy-clinic/dollar-transformed.glb [12.94KB] (95%)
*/

import * as THREE from 'three'
import {useGLTF, useKTX2} from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type {JSX} from "react/jsx-runtime";
import {useEffect, useMemo} from "react";
import {Color} from "three";

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
  }
}

export function Dollar(props: JSX.IntrinsicElements['group'] & {amount: number, pressed: boolean}) {
  const { nodes } = useGLTF('/models/dollar-transformed.glb') as unknown as GLTFResult

  const geometry = useMemo(()=>nodes.Cube.geometry,[nodes])

  const mouseEnter = () => {
    document.body.style.cursor = "pointer";
  }

  const mouseExit = () => {
    document.body.style.cursor = "default";
  }

  const [oneMap, fiveMap, tenMap] = useKTX2(['/textures/1dollar.ktx2',"/textures/5dollar.ktx2","/textures/10dollar.ktx2"])
  const [emitOne,emitFive, emitTen] = useKTX2(['/textures/blank1dollar.ktx2','/textures/blank5dollar.ktx2',"/textures/blank10dollar.ktx2"])
  oneMap.flipY=false
  oneMap.colorSpace = THREE.SRGBColorSpace
  fiveMap.flipY=false
  fiveMap.colorSpace = THREE.SRGBColorSpace
  tenMap.flipY=false
  tenMap.colorSpace = THREE.SRGBColorSpace
  emitOne.flipY=false
  emitFive.flipY=false
  emitTen.flipY=false

  const {amount} = props
  const {map,emit} = useMemo(()=>{
    if(amount===1) return {map:oneMap, emit:emitOne}
    if(amount===5) return {map:fiveMap, emit:emitFive}
    return {map:tenMap, emit:emitTen}
  },[amount, oneMap, fiveMap, tenMap, emitOne, emitFive, emitTen])

  const material = useMemo(() => {
    const mat = new THREE.MeshStandardMaterial({
      color:new Color(.2,.2,.2),
      emissive: new Color(1,1,1)
    })
    return mat
  }, [])

  useEffect(()=>{
    material.map = map
    material.emissiveMap = emit
    material.needsUpdate = true
  },[map, emit, material])

  const {pressed} = props
  useEffect(()=>{
    material.emissiveIntensity = pressed ? 0 : 10
  }, [pressed, material])

  return (
      <mesh {...props} geometry={geometry} scale={props.pressed ? [.055,0.005,0.055] : [.055,.055,.055]}
            name={props.amount as unknown as string} material={material}
            onPointerEnter={mouseEnter} onPointerLeave={mouseExit}
      />
  )
}

useGLTF.preload("/models/dollar-transformed.glb")
useKTX2.preload("/textures/1dollar.ktx2")
useKTX2.preload("/textures/5dollar.ktx2")
useKTX2.preload("/textures/10dollar.ktx2")
useKTX2.preload("/textures/blank1dollar.ktx2")
useKTX2.preload("/textures/blank5dollar.ktx2")
useKTX2.preload("/textures/blank10dollar.ktx2")
