/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 1dollar.glb -T -t 
Files: 1dollar.glb [285.8KB] > /home/jax/Desktop/personal/philanthropy-clinic/dollar-transformed.glb [12.94KB] (95%)
*/

import * as THREE from 'three'
import {Color, Texture, Vector3} from 'three'
import {useGLTF} from '@react-three/drei'
import type {GLTF} from 'three-stdlib'
import type {JSX} from "react/jsx-runtime";
import {useEffect, useMemo, useState} from "react";

type GLTFResult = GLTF & {
    nodes: {
        Cube: THREE.Mesh
    }
}

export function Dollar(props: JSX.IntrinsicElements['group'] & { amount: number, pressed: boolean, map:Texture, emit?:Texture }) {
    const {nodes} = useGLTF('/models/dollar-transformed.glb') as unknown as GLTFResult

    const geometry = useMemo(() => nodes.Cube.geometry, [nodes])

    const mouseEnter = () => {
        if(amount===99 && props.pressed) return
        document.body.style.cursor = "pointer";
    }

    const mouseExit = () => {
        document.body.style.cursor = "default";
    }

    const {amount, map, emit, pressed} = props

    const material = useMemo(() => {
        return new THREE.MeshStandardMaterial({
            color: new Color(.2, .2, .2),
            emissive: new Color(1, 1, 1),
        })
    }, [])


    const [scale, setScale] = useState(new THREE.Vector3(0.055, 0.055, 0.055))

    useEffect(() => {
        if (amount === 99) {
            setScale(new Vector3(0.12, .055, .055))
        }
    }, [amount, setScale])

    useEffect(() => {
        material.map = map
        if(amount===99) material.color = new Color(.75, .75, .75)
        if(emit) material.emissiveMap = emit
        material.needsUpdate = true
    }, [emit, map, material, amount])

    useEffect(() => {
        if (amount === 99) {
            material.emissiveIntensity=0
            material.color = pressed ? new Color(.25, .25, .25) : new Color(.75, .75, .75)
        } else {
            material.emissiveIntensity = pressed ? 0 : 10
        }
    }, [pressed, material, amount])

    return (
        <mesh {...props} geometry={geometry} scale={props.pressed ? [scale.x, scale.y / 2, scale.z] : scale}
              name={props.amount as unknown as string} material={material}
              onPointerEnter={mouseEnter} onPointerLeave={mouseExit}
        />
    )
}

useGLTF.preload("/models/dollar-transformed.glb")
