/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 1dollar.glb -T -t 
Files: 1dollar.glb [285.8KB] > /home/jax/Desktop/personal/philanthropy-clinic/dollar-transformed.glb [12.94KB] (95%)
*/

import * as THREE from 'three'
import {Color, Texture, Vector3} from 'three'
import {useGLTF} from '@react-three/drei'
import type {GLTF} from 'three-stdlib'
import type {JSX} from "react/jsx-runtime";
import {useCallback, useEffect, useMemo, useState} from "react";
import {useA11y} from "@react-three/a11y";

type GLTFResult = GLTF & {
    nodes: {
        Cube: THREE.Mesh
    }
}

export function Dollar(props: JSX.IntrinsicElements['group'] & { amount: number, pressed: boolean, textMap:Texture, emit?:Texture }) {
    const {nodes} = useGLTF('/models/dollar-transformed.glb') as unknown as GLTFResult

    const geometry = useMemo(() => nodes.Cube.geometry, [nodes])

    const a11y = useA11y()

    const {amount, textMap, emit, pressed} = props

    const material = useMemo(() => {
        return new THREE.MeshStandardMaterial({
            color: new Color(.2, .2, .2),
            emissive: new Color(.5, .5, .5),
        })
    }, [])

    const [scale, setScale] = useState(new THREE.Vector3(0.055, 0.055, 0.055))

    useEffect(() => {
        if (amount === 99) {
            setScale(new Vector3(0.12, .055, .055))
        }
    }, [amount, setScale])

    useEffect(() => {
        material.map = textMap
        if(amount===99) {
            material.color = new Color(.75, .75, .75)
            material.emissiveIntensity = 0
        }
        if(emit) material.emissiveMap = emit
        material.needsUpdate = true
    }, [emit, textMap, material, amount])

    const colorPressed = useCallback(()=>{
        return new Color(.25, .25, .25)
    },[])
    const colorUnpressed = useCallback(()=>{
        return new Color(.5, .5, .5)
    },[])
    const colorHover = useCallback(()=>{
        return new Color(.75, .75, .75)
    },[])
    const colorPressedHover = useCallback(()=>{
        return new Color(.3,.3,.3)
    },[])

    const hover = useCallback(()=>{
        if(amount===99){
            material.color = pressed ? colorPressedHover() : colorHover()
            return
        }
        material.color = pressed ? colorPressedHover() : colorHover()
        material.emissiveIntensity = pressed ? 5 : 10
    }, [material, pressed, colorPressedHover, colorHover, amount])

    const unhover = useCallback(()=>{
        if(amount===99) {
            material.color = pressed ? colorPressed() : colorUnpressed()
            return
        }
        material.color = pressed ? colorPressed() : colorUnpressed()
        material.emissiveIntensity = pressed ? 0 : 5
    },[amount, material, pressed, colorPressed, colorUnpressed])

    useEffect(() => {
        if(a11y.hover || a11y.focus){
            hover()
        } else {
            unhover()
        }
    }, [a11y.hover, a11y.focus, hover, unhover])

    return (
        <mesh {...props} geometry={geometry} scale={props.pressed ? [scale.x, scale.y / 2, scale.z] : scale}
              name={props.amount as unknown as string} material={material}
        />
    )
}

useGLTF.preload("/models/dollar-transformed.glb")
