/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 gold-plate.glb -T -t 
Files: gold-plate.glb [1.75MB] > /home/jax/Desktop/personal/philanthropy-clinic/gold-plate-transformed.glb [126.09KB] (93%)
*/

import * as THREE from 'three'
import {useGLTF, useKTX2} from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type {JSX} from "react/jsx-runtime";

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
  }
}

export function GoldPlate(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/models/gold-plate-transformed.glb') as unknown as GLTFResult
  const [plateMap] = useKTX2([
    '/textures/plate.ktx2',
  ])
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} >
          <meshStandardMaterial map={plateMap} metalness={1} roughness={0.65} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/gold-plate-transformed.glb')
