/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 jail.glb -T -t 
Files: jail.glb [35.26KB] > /home/jax/Desktop/personal/philanthropy-clinic/jail-transformed.glb [2.65KB] (92%)
*/

import * as THREE from 'three'
import {Box, useGLTF, useKTX2} from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type {JSX} from "react/jsx-runtime";
import LoginOrDonateMenu from "../groups/LoginOrDonateMenu.tsx";
import {useState} from "react";
import {A11y, useA11y} from "@react-three/a11y";
import {FakeGlowMaterial} from "../materials/FakeGlowMaterial.tsx";

type GLTFResult = GLTF & {
  nodes: {
    jail: THREE.Mesh
  }
}

function JailBox(props:{showBox:boolean}){
    const a11y = useA11y()
    return (
        <Box args={[3, 3, 3]}>
            {(a11y.focus && props.showBox)
                ? <FakeGlowMaterial />
                : <meshStandardMaterial color="white" transparent opacity={0} />}
        </Box>
    )
}

export function Jail(props: JSX.IntrinsicElements['group'] & {jailState?: boolean}) {
  const { nodes } = useGLTF('/models/jail-transformed.glb') as unknown as GLTFResult

  const jailMap = useKTX2('textures/jail.ktx2');

  const [panelState, setPanelState] = useState<boolean>(false);

  const onClick = () => {
      if (props.jailState || panelState) return;
      setPanelState(true);
      document.body.style.cursor = "default";
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      (window as any).umami?.track('panel_opened');
  }

  return (<>
    <group {...props} dispose={null}>
        <A11y role={"button"} description={"A jail holding a carrot."} actionCall={onClick}
              tabIndex={panelState ? -1 : 0}>
            <JailBox showBox={!panelState}/>
        </A11y>
      <mesh geometry={nodes.jail.geometry}>
          <meshStandardMaterial map={jailMap} roughness={.2} metalness={0.3}/>
      </mesh>
    </group>
    <LoginOrDonateMenu panelState={panelState} setPanelState={setPanelState} /></>
  )
}

useKTX2.preload("/textures/jail.ktx2")
useGLTF.preload('/models/jail-transformed.glb')
