/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 jail.glb -T -t 
Files: jail.glb [35.26KB] > /home/jax/Desktop/personal/philanthropy-clinic/jail-transformed.glb [2.65KB] (92%)
*/

import * as THREE from 'three'
import {Box, useGLTF, useKTX2} from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type {JSX} from "react/jsx-runtime";
import LoginOrDonateMenu from "../groups/LoginOrDonateMenu.tsx";
import {useState} from "react";

type GLTFResult = GLTF & {
  nodes: {
    jail: THREE.Mesh
  }
}

export function Jail(props: JSX.IntrinsicElements['group'] & {jailState?: boolean}) {
  const { nodes } = useGLTF('/models/jail-transformed.glb') as unknown as GLTFResult

  const jailMap = useKTX2('textures/jail.ktx2');

  const [panelState, setPanelState] = useState<boolean>(false);

  const onPointerEnter = () => {
      if (props.jailState || panelState) return;
      document.body.style.cursor = "pointer";
  }

  const onPointerLeave = () => {
      if (props.jailState || panelState) return;
        document.body.style.cursor = "default";
  }

  const onClick = () => {
      if (props.jailState || panelState) return;
      setPanelState(true);
      document.body.style.cursor = "default"
  }

  const invisMat = new THREE.MeshStandardMaterial({color: 'white', opacity: 0, transparent: true});

  return (<>
    <group {...props} dispose={null}>
        <Box material={invisMat} args={[3, 3, 3]} onPointerEnter={onPointerEnter} onPointerLeave={onPointerLeave} onClick={onClick}/>
      <mesh geometry={nodes.jail.geometry}>
          <meshStandardMaterial map={jailMap}/>
      </mesh>
    </group>
    <LoginOrDonateMenu panelState={panelState} setPanelState={setPanelState} /></>
  )
}

useKTX2.preload("/textures/jail.ktx2")
useGLTF.preload('/models/jail-transformed.glb')
