/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 light.glb -T -t 
Files: light.glb [13.69KB] > /home/jax/Desktop/personal/philanthropy-clinic/light-transformed.glb [3.72KB] (73%)
*/

import * as THREE from 'three'
import {MeshTransmissionMaterial, useGLTF} from '@react-three/drei'
import type {GLTF} from 'three-stdlib'
import type {JSX} from "react/jsx-runtime";
import {useEffect, useMemo} from "react";
import {CREATED, type EmailState, OFF, VALID} from "../EmailState.tsx";


type GLTFResult = GLTF & {
    nodes: {
        Cube: THREE.Mesh
        Cube_1: THREE.Mesh
        emiter: THREE.Mesh
    }
    materials: {
        glass: THREE.MeshStandardMaterial
        base: THREE.MeshStandardMaterial
        ['Material.001']: THREE.MeshStandardMaterial
    }
}


export function Light(props: JSX.IntrinsicElements['group'] & {emailValid:EmailState}) {
    const {nodes, materials} = useGLTF('/light-transformed.glb') as unknown as GLTFResult

    const emitMat = useMemo(()=>new THREE.MeshStandardMaterial({
        emissiveIntensity: 50,
    }),[])

    useEffect(() => {
        if(!emitMat) return
        switch(props.emailValid){
            case VALID:
                emitMat.color.setRGB(1,1,0)
                break
            case CREATED:
                emitMat.color.setRGB(0,1,0)
                break
            case OFF:
            default:
                emitMat.color.setRGB(1,0,0)
                break
        }
    },[props.emailValid, emitMat])

    return (
        <group {...props} dispose={null}>
                <mesh geometry={nodes.Cube.geometry} scale={[.75,.5,1]}>
                    <MeshTransmissionMaterial roughness={.8} thickness={0.5} />
                </mesh>
            <mesh geometry={nodes.emiter.geometry} material={emitMat} rotation={[0,0,1]} scale={.4} position={[0,1,0]}/>
            <mesh geometry={nodes.emiter.geometry} material={emitMat} rotation={[0,1.56,1]} scale={.4} position={[-.1,1,0.05]}/>
            <mesh geometry={nodes.Cube_1.geometry} material={materials.base}/>
        </group>
    )
}

useGLTF.preload('/light-transformed.glb')
