/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 carrot.glb -t -T 
Files: carrot.glb [8.56KB] > /home/jax/Desktop/personal/philanthropy-clinic/carrot-transformed.glb [2.47KB] (71%)
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type {GLTF} from 'three-stdlib';
import type {JSX} from "react/jsx-runtime";

type GLTFResult = GLTF & {
  nodes: {
    Cone: THREE.Mesh
    Cone_1: THREE.Mesh
  }
  materials: {
    carrot: THREE.MeshStandardMaterial
    leaf: THREE.MeshStandardMaterial
  }
}

export function Carrot(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/carrot-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cone.geometry} material={materials.carrot} />
      <mesh geometry={nodes.Cone_1.geometry} material={materials.leaf} />
    </group>
  )
}

useGLTF.preload('/carrot-transformed.glb')
