/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 1dollar.glb -T -t 
Files: 1dollar.glb [285.8KB] > /home/jax/Desktop/personal/philanthropy-clinic/dollar-transformed.glb [12.94KB] (95%)
*/

import * as THREE from 'three'
import {useGLTF, useTexture} from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type {JSX} from "react/jsx-runtime";
import {useEffect, useState} from "react";
import {Color, Texture} from "three";

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
  }
}

export function Dollar(props: JSX.IntrinsicElements['group'] & {amount: number, pressed: boolean}) {
  const { nodes } = useGLTF('/dollar-transformed.glb') as unknown as GLTFResult

  const mouseEnter = () => {
    document.body.style.cursor = "pointer";
  }

  const mouseExit = () => {
    document.body.style.cursor = "default";
  }

  const [scale, setScale] = useState<[number,number,number]>([1,1,1]);

  useEffect(() => {
    setScale(props.pressed ? [1,0.5,1] : [1,1,1])
  },[props.pressed])

  const [oneMap, fiveMap, tenMap] = useTexture(['/textures/1dollar.png',"/textures/5dollar.png","/textures/10dollar.png"])
  const [emitOne,emitFive, emitTen] = useTexture(['/textures/blank1dollar.png','/textures/blank5dollar.png',"/textures/blank10dollar.png"])
  oneMap.flipY=false
  fiveMap.flipY=false
  tenMap.flipY=false
  emitOne.flipY=false
  emitFive.flipY=false
  emitTen.flipY=false

  let activeMap: Texture
  let activeEmit: Texture
  if (props.amount===1){
    activeMap = oneMap
    activeEmit = emitOne
  } else if (props.amount===5){
    activeMap=fiveMap
    activeEmit = emitFive
  } else {
    activeMap=tenMap
    activeEmit = emitTen
  }

  const newMat = new THREE.MeshStandardMaterial()
  newMat.map=activeMap
  newMat.emissive=new Color(1,1,1)
  newMat.emissiveMap=activeEmit
  newMat.emissiveIntensity=props.pressed?0:2
  const gray = .2
  newMat.color=new THREE.Color(gray,gray,gray)

  return (
    <group {...props} dispose={null} name={props.amount as unknown as string}>
      <mesh geometry={nodes.Cube.geometry} scale={scale} material={newMat} onPointerEnter={mouseEnter} onPointerLeave={mouseExit}
      />
    </group>
  )
}

useGLTF.preload('/dollar-transformed.glb')
useTexture.preload(['/textures/1dollar.png',"/textures/5dollar.png", "/textures/10dollar.png"])
useTexture.preload(["/textures/blank1dollar.png","/textures/blank5dollar.png","/textures/blank10dollar.png"])
