/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 gold-plate.glb -T -t 
Files: gold-plate.glb [1.75MB] > /home/jax/Desktop/personal/philanthropy-clinic/gold-plate-transformed.glb [126.09KB] (93%)
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type {JSX} from "react/jsx-runtime";
import {Container, Fullscreen, Text} from "@react-three/uikit";

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
  }
  materials: {
    ['pc-mat']: THREE.MeshStandardMaterial
  }
}

export function GoldPlate(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/gold-plate-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['pc-mat']} />
    </group>
  )
}

useGLTF.preload('/gold-plate-transformed.glb')
