/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 jail.glb -T -t 
Files: jail.glb [35.26KB] > /home/jax/Desktop/personal/philanthropy-clinic/jail-transformed.glb [2.65KB] (92%)
*/

import * as THREE from 'three'
import {Box, useGLTF} from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type {JSX} from "react/jsx-runtime";
import {useLoader} from "@react-three/fiber";
import {TextureLoader} from "three";
import LoginOrDonateMenu from "./LoginOrDonateMenu.tsx";
import {useState} from "react";

type GLTFResult = GLTF & {
  nodes: {
    jail: THREE.Mesh
  }
}

export function Jail(props: JSX.IntrinsicElements['group'] & {jailState?: boolean}) {
  const { nodes } = useGLTF('/jail-transformed.glb') as unknown as GLTFResult

  const [color, rough] = useLoader(TextureLoader, [
      'textures/jail-color.avif',
      'textures/jail-rough.avif',
  ]);

  const [panelState, setPanelState] = useState<boolean>(false);

  const onPointerEnter = () => {
      if (props.jailState) return;
      document.body.style.cursor = "pointer";
  }

  const onPointerLeave = () => {
      if (props.jailState) return;
        document.body.style.cursor = "default";
  }

  const onClick = () => {
      setPanelState(true);
  }

  const invisMat = new THREE.MeshStandardMaterial({color: 'white', opacity: 0, transparent: true});

  return (<>
    <group {...props} dispose={null}>
        <Box material={invisMat} args={[3, 3, 3]} onPointerEnter={onPointerEnter} onPointerLeave={onPointerLeave} onClick={onClick}/>
      <mesh geometry={nodes.jail.geometry}>
          <meshStandardMaterial map={color} roughnessMap={rough}
          metalness={1}/>
      </mesh>
    </group>
    <LoginOrDonateMenu panelState={panelState} setPanelState={setPanelState} /></>
  )
}

useGLTF.preload('/jail-transformed.glb')
