/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 jail.glb -T -t 
Files: jail.glb [35.26KB] > /home/jax/Desktop/personal/philanthropy-clinic/jail-transformed.glb [2.65KB] (92%)
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type {JSX} from "react/jsx-runtime";
import {useLoader} from "@react-three/fiber";
import {TextureLoader} from "three";

type GLTFResult = GLTF & {
  nodes: {
    jail: THREE.Mesh
  }
}

export function Jail(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/jail-transformed.glb') as unknown as GLTFResult

  const [color, rough] = useLoader(TextureLoader, [
      'textures/jail-color.avif',
      'textures/jail-rough.avif',
  ]);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.jail.geometry}>
          <meshStandardMaterial map={color} roughnessMap={rough}
          metalness={1}/>
      </mesh>
    </group>
  )
}

useGLTF.preload('/jail-transformed.glb')
