/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 light.glb -T -t 
Files: light.glb [13.69KB] > /home/jax/Desktop/personal/philanthropy-clinic/light-transformed.glb [3.72KB] (73%)
*/

import * as THREE from 'three'
import {Color} from 'three'
import {MeshTransmissionMaterial, useGLTF} from '@react-three/drei'
import type {GLTF} from 'three-stdlib'
import type {JSX} from "react/jsx-runtime";
import {useEffect, useState} from "react";


type GLTFResult = GLTF & {
    nodes: {
        Cube: THREE.Mesh
        Cube_1: THREE.Mesh
        emiter: THREE.Mesh
    }
    materials: {
        glass: THREE.MeshStandardMaterial
        base: THREE.MeshStandardMaterial
        ['Material.001']: THREE.MeshStandardMaterial
    }
}

export function Light(props: JSX.IntrinsicElements['group'] & {emailValid:number}) {
    const {nodes, materials} = useGLTF('/light-transformed.glb') as unknown as GLTFResult

    const [emitColor, setEmitColor] = useState<Color>(new Color(1,0,0))

    const emitMat = new THREE.MeshStandardMaterial({
        color: emitColor,
        emissive: emitColor,
        emissiveIntensity: 10
    })

    useEffect(() => {
        if (props.emailValid==0){
            setEmitColor(new Color(1,0,0))
        }
        else if (props.emailValid==1){
            setEmitColor(new Color(1,1,0))
        }
        else if (props.emailValid==2){
            setEmitColor(new Color(0,1,0))
        }
    },[props.emailValid])

    return (
        <group {...props} dispose={null}>
                <mesh geometry={nodes.Cube.geometry} scale={[.75,.5,1]}>
                    <MeshTransmissionMaterial roughness={.8} thickness={0.5} />
                </mesh>
            <mesh geometry={nodes.emiter.geometry} material={emitMat} rotation={[0,0,1]} scale={.4} position={[0,1,0]}/>
            <mesh geometry={nodes.emiter.geometry} material={emitMat} rotation={[0,1.56,1]} scale={.4} position={[-.1,1,0.05]}/>
            <mesh geometry={nodes.Cube_1.geometry} material={materials.base}/>
        </group>
    )
}

useGLTF.preload('/light-transformed.glb')
