/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pig.glb -t -T 
Files: pig.glb [50.29KB] > /home/jax/Desktop/personal/philanthropy-clinic/pig-transformed.glb [19.07KB] (62%)
*/

import * as THREE from 'three'
import {useEffect, useMemo, useRef} from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import {type GLTF, SkeletonUtils } from 'three-stdlib'
import IntrinsicElements = React.JSX.IntrinsicElements;

type ActionName = 'ArmatureAction'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    eye: THREE.Mesh
    pig: THREE.SkinnedMesh
    Bone: THREE.Bone
    Bone002: THREE.Bone
    Bone005: THREE.Bone
    Bone007: THREE.Bone
    Bone009: THREE.Bone
    Bone011: THREE.Bone
  }
  materials: {
    eye: THREE.MeshStandardMaterial
    pig: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Pig(props: IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { scene, animations } = useGLTF('/pig-transformed.glb')
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)

    useEffect(() => {
        if(actions?.ArmatureAction){
            actions.ArmatureAction.play();
        }
    }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.Bone} />
          <primitive object={nodes.Bone002} />
          <primitive object={nodes.Bone005} />
          <primitive object={nodes.Bone007} />
          <primitive object={nodes.Bone009} />
          <primitive object={nodes.Bone011} />
        </group>
        <skinnedMesh name="pig" geometry={nodes.pig.geometry} material={materials.pig} skeleton={nodes.pig.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/pig-transformed.glb')
