/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pig.glb -T -t 
Files: pig.glb [73.97KB] > /home/jax/Desktop/personal/philanthropy-clinic/pig-transformed.glb [34.9KB] (53%)
*/

import * as THREE from 'three'
import React, {useEffect} from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import {type GLTF, SkeletonUtils } from 'three-stdlib'
import type {JSX} from "react/jsx-runtime"

type ActionName = 'Breathe' | 'Jump'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Sphere: THREE.SkinnedMesh
    Sphere_1: THREE.SkinnedMesh
    pig: THREE.SkinnedMesh
    Bone: THREE.Bone
    Bone002: THREE.Bone
    Bone005: THREE.Bone
    Bone007: THREE.Bone
    Bone009: THREE.Bone
    Bone011: THREE.Bone
  }
  materials: {
    eye: THREE.MeshStandardMaterial
    pupil: THREE.MeshStandardMaterial
    pig: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Pig(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null!)
  const { scene, animations } = useGLTF('/pig-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions.Breathe?.play()
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[0, 0, -0.497]} rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.Bone} />
          <primitive object={nodes.Bone002} />
          <primitive object={nodes.Bone005} />
          <primitive object={nodes.Bone007} />
          <primitive object={nodes.Bone009} />
          <primitive object={nodes.Bone011} />
        </group>
        <group name="eye" position={[0, 0, -0.497]} rotation={[Math.PI / 2, 0, 0]}>
          <skinnedMesh name="Sphere" geometry={nodes.Sphere.geometry} material={materials.eye} skeleton={nodes.Sphere.skeleton} />
          <skinnedMesh name="Sphere_1" geometry={nodes.Sphere_1.geometry} material={materials.pupil} skeleton={nodes.Sphere_1.skeleton} />
        </group>
        <skinnedMesh name="pig" geometry={nodes.pig.geometry} material={materials.pig} skeleton={nodes.pig.skeleton} position={[0, 0, -0.497]} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/pig-transformed.glb')
